#u/usr/bin/env bash

# Change prefix from 'Ctrl+B' to 'Ctrl+A'.
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

#Disable exit-empty.
set -s exit-empty on

# Start counting pane and window number at 0.
set -g base-index 0
setw -g pane-base-index 0

# Disable automatic renaming.
set-option -wg automatic-rename off

# Allow tmux to use transparent bg color.
set-option -ga terminal-overrides ",xterm-256color:Tc"
set -g default-terminal "xterm-kitty"

# Bind Prefix + t to clock mode.
bind C-t clock-mode

# Enable mouse control.
set -g mouse on

# Instruct tmux to forward clipboard sequences to the outer terminal
set -g set-clipboard on

# Required for tmux >= 3.3: allow escape sequence passthrough per-pane
set -g allow-passthrough on
set -g focus-events on

# Sync host clipboard into tmux buffer on focus (adjust command for your OS)
# For X11
set-hook -g pane-focus-in  'run-shell "xclip -selection clipboard -o | tmux load-buffer -"'

# For Wayland
# set-hook -g pane-focus-in  'run-shell "wl-paste --no-newline | tmux load-buffer -"'

# Tmux status position.
set-option -g status-position bottom

# THEMES SECTION

# Tokyonight.
# set -g @tokyo-night-tmux_theme "day"
# run-shell "~/.config/tmux/tokyo-night-tmux/tokyo-night.tmux"
# set -g @tokyo-night-tmux_window_id_style digital
# set -g @tokyo-night-tmux_pane_id_style hsquare
# set -g @tokyo-night-tmux_zoom_id_style dsquare

# Icon styles.
# set -g @tokyo-night-tmux_terminal_icon 
# set -g @tokyo-night-tmux_active_terminal_icon 
# set -g @tokyo-night-tmux_window_tidy_icons 0 # No extra spaces between icons.

# Solarized theme.
# source ~/.config/tmux/custom/solarized-tmux.conf

# Rose-pine theme.
# source ~/.config/tmux/custom/rose-pine-tmux.conf

# Catppuccin theme.
# set -g @catppuccin_flavor "latte"
# set -g @catppuccin_window_status_style "rounded"
# run ~/.config/tmux/catppuccin/tmux/catppuccin.tmux
# set -g status-right-length 100
# set -g status-left-length 100
# set -g status-left ""
# set -g status-right "#{E:@catppuccin_status_application}"
# set -ag status-right "#{E:@catppuccin_status_session}"

# List of plugins.
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-strategy-nvim 'session'
set -g @plugin 'tmux-plugins2kabhishek/tmux2k'
# set -g @tmux2k-theme 'gruvbox'
# set -g @tmux2k-theme 'duoblue'
# set -g @tmux2k-theme 'duo'
# set -g @tmux2k-theme 'default'
set -g @tmux2k-theme 'catppuccin'
set -g @tmux2k-show-powerline true
set -g @tmux2k-icons-only false

# Gruvbox theme. (via tpm)
# set -g @plugin 'egel/tmux-gruvbox'
# set -g @tmux-gruvbox 'dark' # or 'dark256', 'light', 'light256'

# Reload config file.
bind r source-file ~/.config/tmux/tmux.conf

# Initialize TMUX plugin manager.
run '~/.tmux/plugins/tpm/tpm'
