# Config file for kitty.

# Window initial width and height.
initial_window_width 137c
initial_window_height 33c
hide_window_decorations yes

# Window opacity
# background_opacity 0.85
# background_blur 1

# Font settings
# Ensure the fonts are installed, for  symbols install  ttf-jetbrains-mono-nerd

# JetBrainsMono (Light)
# font_family      family='JetBrainsMono Nerd Font Mono' style=SemiBold features='+calt +ss19 +zero'
# font_size 13
# adjust_line_height 105%
# adjust_column_width 100%
# bold_font        auto
# italic_font      auto
# bold_italic_font auto

# JetBrainsMono (Dark)
# font_family      family='JetBrainsMono Nerd Font Mono' style=ExtraLight features='+calt +ss19 +zero'
# font_size 13
# adjust_line_height 105%
# adjust_column_width 100%
# bold_font        auto
# italic_font      auto
# bold_italic_font auto

# Gitlab mono (Light)
# font_family      family='GitLab Mono' variable_name=GitLabMono wght=474.8633879781421
# font_family      family='GitLab Mono' style=SemiBold
# font_size 13
# adjust_line_height 105%
# adjust_column_width 100%
# bold_font        auto
# italic_font      auto
# bold_italic_font auto

# Gitlab mono (Dark)
# font_family      family='GitLab Mono' style=Light
# font_family      family='GitLab Mono' style=Regular
# font_size 13
# adjust_line_height 105%
# adjust_column_width 100%
# bold_font        auto
# italic_font      auto
# bold_italic_font auto

# Gitlab mono (Dark) large font
# font_family      family='GitLab Mono' style=Light
font_family      family='GitLab Mono' style=Regular
font_size 13
adjust_line_height 105%
adjust_column_width 100%
bold_font        auto
italic_font      auto
bold_italic_font auto

# Liga SFMono (Light)
# font_family      family='Liga SFMono Nerd Font' style=Medium features='+calt +ss03 +ss04'
# font_size 13.5
# adjust_line_height 105%
# adjust_column_width 95%
# bold_font        auto
# italic_font      auto
# bold_italic_font auto

# Liga SFMono (Dark)
# font_family      family='Liga SFMono Nerd Font' style=Regular features='+calt +ss03 +ss04'
# font_size 13.5
# adjust_line_height 110%
# adjust_column_width 95%
# bold_font        auto
# italic_font      auto
# bold_italic_font auto

# UbuntuMono (both)
# font_family      family='UbuntuMono Nerd Font Mono' style=Regular
# adjust_line_height 110%
# adjust_column_width 95%
# font_size 15
# bold_font        auto
# italic_font      auto
# bold_italic_font auto

# Recommended for Light theme. (Maple Mono)
# font_family Maple Mono
# font_size 13
# adjust_line_height 0
# modify_font cell_width 100%
# modify_font cell_height 100%

# Recommended for Dark theme. (Maple Mono)
# font_family Maple Mono Light
# font_size 14
# adjust_line_height 0
# modify_font cell_width 100%
# modify_font cell_height 100%
