# Config file for kitty.

# Window initial width and height.
initial_window_width 137c
initial_window_height 33c
hide_window_decorations yes

# Window opacity
# background_opacity 0.9
# background_blur 1

# Font settings

# JetBrainsMono (Dark)
# font_family      family='JetBrainsMono Nerd Font Mono' style=ExtraLight features='+calt +ss19 +zero'
# font_size 13
# adjust_line_height 105%
# adjust_column_width 100%
# bold_font        auto
# italic_font      auto
# bold_italic_font auto

# Gitlab mono (Dark)
# font_family      family='GitLab Mono' style=Light
# font_size 13
# adjust_line_height 105%
# adjust_column_width 98%
# bold_font        auto
# italic_font      auto
# bold_italic_font auto

# Gitlab mono (Light)
font_family      family='GitLab Mono' variable_name=GitLabMono wght=474.8633879781421
font_size 13
adjust_line_height 105%
adjust_column_width 100%
bold_font        auto
italic_font      auto
bold_italic_font auto

# Liga SFMono (Light)
# font_family      family='Liga SFMono Nerd Font' style=Medium features='+calt +ss03 +ss04'
# font_size 13
# adjust_line_height 100%
# adjust_column_width 100%
# bold_font        auto
# italic_font      auto
# bold_italic_font auto

# Liga SFMono (Dark)
# font_family      family='Liga SFMono Nerd Font' style=Regular features='+calt +ss03 +ss04'
# font_size 13.5
# adjust_line_height 110%
# adjust_column_width 100%
# bold_font        auto
# italic_font      auto
# bold_italic_font auto

# UbuntuMono (both)
# font_family      family='UbuntuMono Nerd Font Mono' style=Regular
# adjust_line_height 110%
# adjust_column_width 95%
# font_size 15
# bold_font        auto
# italic_font      auto
# bold_italic_font auto


# Recommended for Light theme. (Maple Mono)
# font_family Maple Mono
# font_size 13
# adjust_line_height 0
# modify_font cell_width 100%
# modify_font cell_height 100%

# Recommended for Dark theme. (Maple Mono)
# font_family Maple Mono Light
# font_size 14
# adjust_line_height 0
# modify_font cell_width 100%
# modify_font cell_height 100%


# Clipboard settings
# clipboard_control write-clipboard write-primary read-clipboard read-primary no-append
clipboard_control write-clipboard write-primary read-clipboard read-primary


# Map Nerd Font icon ranges using separate, shorter lines
symbol_map U+e000-U+e00a,U+e0a0-U+e0a2,U+e0a3 Symbols Nerd Font
symbol_map U+e0b0-U+e0b3,U+e0b4-U+e0c8,U+e0ca Symbols Nerd Font
symbol_map U+e0cc-U+e0d7,U+e200-U+e2a9,U+e300-U+e3e3 Symbols Nerd Font
symbol_map U+e5fa-U+e6b7,U+e700-U+e8ef,U+ea60-U+ec1e Symbols Nerd Font
symbol_map U+ed00-U+efce,U+f000-U+f2ff,U+f300-U+f381 Symbols Nerd Font
symbol_map U+f400-U+f533,U+f0001-U+f1af0 Symbols Nerd Font
